import localFont from "next/font/local";
import "./globals.css";
import Root from "./components/Root";
import NavBar from "./components/navbar";
import SideBar from "./components/sidebar";
import CartProvider from "./components/Cart";
import { Analytics } from "@vercel/analytics/react";

const RedHatNorm = localFont({
  src: "./fonts/RedHat.ttf",
  variable: "--font-redhat-norm",
  weight: "100 900",
});
const redHatItalic = localFont({
  src: "./fonts/RedHatItalic.ttf",
  variable: "--font-redhat-italic",
  weight: "100 900",
});

export const metadata = {
  title: "e-shop",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "light" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' theme='dark'>
      <body className={`${RedHatNorm.variable} ${redHatItalic.variable}`}>
        <CartProvider>
          <Root navbar={<NavBar />} sidebar={<SideBar />}>
            {children}
          </Root>
        </CartProvider>
        <Analytics />
      </body>
    </html>
  );
}
