import localFont from "next/font/local";
import "./globals.css";
import Root from "./components/Root";
import NavBar from "./components/navbar";
import SideBar from "./components/sidebar";
import CartProvider from "./components/Cart";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "e-shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CartProvider>
          <Root navbar={<NavBar />} sidebar={<SideBar />}>
            {children}
          </Root>
        </CartProvider>
      </body>
    </html>
  );
}
